In [ ]:
import numpy as np

a = np.arange(6).reshape(2, 3)
b = np.arange(8).reshape(2, 4)

a, b

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]))

In [ ]:
a = a * 5
b = b * 5

a, b

(array([[  0,  25,  50],
        [ 75, 100, 125]]),
 array([[  0,  25,  50,  75],
        [100, 125, 150, 175]]))

In [ ]:
a.max()


125

In [ ]:
b.max()

175